service: hads

provider:
  name: aws
  runtime: nodejs8.10
  role: arn:aws:iam::179962611012:role/lambda-vpc-execution
  vpc:
    securityGroupIds:
      - sg-01ac88f4c68943c70
      - sg-00a9e2368ad637fec
    subnetIds:
      - subnet-0985efca552edf29d
      - subnet-0c4dd45568d1cab75
      - subnet-0cb0e83bc8ca442aa
      - subnet-05d117aed8b9f62cb
      - subnet-031f024b940aa3b2c
      - subnet-0e3c1327ce9d020c4

plugins:
  - serverless-offline


functions:
  graphql:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
